
[tool.poetry]
name = "gale-shapley"
version = "0.1.0"
description = ""
authors = ["aricma <adrian@aricma.com>"]

[tool.poetry.dependencies]
python = "3.8.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
